MATERIAL_TABLE = "Material"
MATERIAL_SECTION_TABLE = "MaterialSection"
MATERIAL_PAGE_TABLE = "MaterialPage"
RECORDING_TABLE = "Recording"
TRANSCRIPT_SEGMENT_TABLE = "TranscriptSegment"
QUIZ_TABLE = "Quiz"
QUIZ_QUESTION_TABLE = "QuizQuestion"
QUIZ_ATTEMPT_TABLE = "QuizAttempt"
QUIZ_ATTEMPT_ANSWER_TABLE = "QuizAttemptAnswer"
QUIZ_GENERATION_JOB_TABLE = "QuizGenerationJob"
SESSION_TABLE = "Session"

MATERIAL_STATUS_UPLOADED = "uploaded"
MATERIAL_STATUS_QUEUED = "queued"
MATERIAL_STATUS_PROCESSING = "processing"
MATERIAL_STATUS_COMPLETED = "completed"
MATERIAL_STATUS_FAILED = "failed"

STT_STATUS_UPLOADED = "uploaded"
STT_STATUS_QUEUED = "queued"
STT_STATUS_TRANSCRIBING = "transcribing"
STT_STATUS_POST_PROCESSING = "post_processing"
STT_STATUS_COMPLETED = "completed"
STT_STATUS_FAILED = "failed"

QUIZ_STATUS_DRAFT = "draft"
QUIZ_STATUS_PUBLISHED = "published"
QUIZ_STATUS_HIDDEN = "hidden"

JOB_STATUS_QUEUED = "queued"
JOB_STATUS_PROCESSING = "processing"
JOB_STATUS_COMPLETED = "completed"
JOB_STATUS_FAILED = "failed"

DEFAULT_POLL_INTERVAL_SECONDS = 5
DEFAULT_BATCH_SIZE = 5
DEFAULT_MAX_RETRIES = 3
DEFAULT_BACKOFF_BASE_SECONDS = 2
DEFAULT_WORKER_TIMEOUT_SECONDS = 30
